---
{
  "kind": "pipeline",
  "name": "Kubernetes",
  "node_selector": { "drone": true },
  "platform": { "arch": "amd64", "os": "linux" },
  "steps":
    [
      {
        "commands":
          [
            "npm install prettier",
            "echo .pre-commit-config.yaml >> .prettierignore",
            'npx prettier --check "**/*.{ts,js,md,yaml,yml,sass,css,scss,html,htm}"',
          ],
        "image": "node:lts-buster",
        "name": "Prettier lint",
        "pull": "always",
      },
      {
        "environment": { "DOCKER_BUILDKIT": 1 },
        "image": "plugins/docker",
        "name": "Build container image",
        "pull": "always",
        "settings": { "dry_run": true, "purge": true, "repo": "build-only" },
        "trigger": { "event": ["pull_request"] },
        "when": { "branch": { "exclude": ["master"] } },
      },
      {
        "environment": { "DOCKER_BUILDKIT": 1 },
        "image": "plugins/docker",
        "name": "Publish image kradalby/glossary",
        "pull": "always",
        "settings":
          {
            "password": { "from_secret": "docker_password" },
            "purge": true,
            "repo": "kradalby/glossary",
            "tags":
              [
                "latest",
                "latest-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}",
                "${DRONE_COMMIT_SHA:0:8}",
              ],
            "username": { "from_secret": "docker_username" },
          },
        "when": { "branch": ["master"], "event": ["push"] },
      },
      {
        "commands":
          [
            'container-file-extractor "kradalby/glossary" "${DRONE_COMMIT_SHA:0:8}" "usr/share/nginx/html"',
            "mkdir -p dist/",
            "mv output/usr/share/nginx/html/* dist/.",
          ],
        "image": "kradalby/container-file-extractor:latest",
        "name": "Extract from container",
        "pull": "always",
        "when": { "branch": ["master"], "event": ["push"] },
      },
      {
        "image": "plugins/gh-pages",
        "name": "Publish to GitHub Pages",
        "pull": "always",
        "settings":
          {
            "pages_directory": "dist",
            "password": { "from_secret": "github_pages_push_token" },
            "username": { "from_secret": "github_pages_push_user" },
          },
        "when": { "branch": ["master"], "event": ["push"] },
      },
    ],
  "type": "kubernetes",
}
